name: Go CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build, Test, Lint and Analyze
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      GOPROXY: https://proxy.golang.org,direct
      GOTOOLCHAIN: go1.26.0+auto

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.26.x"
        cache: true

    - name: Start Redis with Password and No-Save
      run: |
        docker run -d -p 6379:6379 --name ci-redis redis:alpine \
          redis-server --requirepass root --save "" --appendonly no

    - name: Wait for Redis to be ready
      run: |
        for i in {1..10}; do
          if echo "PING" | nc -w 2 localhost 6379 > /dev/null; then
            echo "Redis is ready";
            break;
          fi;
          echo "Waiting for Redis...";
          sleep 3;
        done

    - name: Run Lint, Build and Test
      run: |
        make lint
        make vet
        make build
        make test